batch_size: 64
workers: 0
nepoch: 120
model_name: vrcnet 
load_model: ./log/vrcnet_cd_debug_2022-02-22T17:07:04/pretrain.pth
load_model2: ./log/vrcnet_cd_debug_2022-02-22T17:07:04/best_f1_network_refinement_16384.pth
start_epoch: 0
num_points: 2048
num_points_step2: 16384
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: False
points_label: True
num_coarse_raw: 1024
num_fps: 2048
num_coarse: 2048

# test
save_vis: False
eval_emd: False